version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - pip install -r requirements.txt
      - npm install aws-cdk -g
  build:
    commands:
      - cdk synth
  post_build:
    commands:
      - aws s3 cp cdk.out/MeshVpcCDKStack.clean.template.json  s3://nycmesh-cloudformation-templates/MeshVpcCDKStack/MeshVpcCDKStack.clean.template.json


artifacts:
  files: cdk.out/*