version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - pip install -r requirements.txt
      - npm install aws-cdk -g
  build:
    commands:
      - cdk synth

artifacts:
  files: cdk.out/*